namespace JonathanHandProject2.Model;

/// <summary>
/// Represents a single high score entry recorded at the end of
/// a completed game round. Each entry stores the player's name,
/// the total score achieved, and the amount of time (in seconds)
/// the player used during that round.
///
/// These entries are stored by the HighScoreBoard, displayed in
/// the HighScoreForm UI, and saved/loaded through JSON persistence.
/// </summary>
public class HighScoreEntry
{
    /// <summary>
    /// The name entered by the player for this game round.
    /// </summary>
    public string PlayerName { get; }

    /// <summary>
    /// The final calculated score for the round. This value is
    /// generated by summing the scores of all valid word attempts.
    /// </summary>
    public int Score { get; }

    /// <summary>
    /// The total number of seconds the player used before ending
    /// the round (either through time expiration or manual end).
    /// </summary>
    public int TimeSeconds { get; }

    /// <summary>
    /// Creates a new high score entry with the provided player
    /// name, score value, and total time used.
    /// </summary>
    /// <param name="playerName">The name of the player.</param>
    /// <param name="score">The score achieved during the round.</param>
    /// <param name="timeSeconds">The time consumed in seconds.</param>
    public HighScoreEntry(string playerName, int score, int timeSeconds)
    {
        PlayerName = playerName;
        Score = score;
        TimeSeconds = timeSeconds;
    }
}