namespace JonathanHandProject2
{
    /// <summary>
    /// Designer-generated portion of the HighScoreForm class.
    /// 
    /// This file is responsible ONLY for constructing and laying out
    /// the user interface controls for the high score window. It does
    /// not contain any game logic — that lives in HighScoreForm.cs.
    ///
    /// Key UI elements created here:
    ///   • scoreGrid — DataGridView showing high score entries
    ///   • resetButton — clears all high scores
    ///   • closeButton — closes the form
    ///
    /// All styling, positioning, and column definitions for the grid
    /// are also set here.
    /// </summary>
    partial class HighScoreForm
    {
        private System.ComponentModel.IContainer? components = null;

        /// <summary>
        /// Releases UI resources created by the designer.
        /// This is called automatically when the form closes.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null)
                components.Dispose();

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Method automatically generated by the Windows Forms designer.
        /// 
        /// Builds the entire UI layout:
        ///   • Creates the DataGridView and columns
        ///   • Positions the Reset and Close buttons
        ///   • Applies styling to the grid (fonts, alignment, colors)
        ///   • Sets form size and load behavior
        /// </summary>
        private void InitializeComponent()
        {
            this.scoreGrid = new DataGridView();
            this.PlayerCol = new DataGridViewTextBoxColumn();
            this.ScoreCol = new DataGridViewTextBoxColumn();
            this.TimeCol = new DataGridViewTextBoxColumn();
            this.resetButton = new Button();
            this.closeButton = new Button();

            ((System.ComponentModel.ISupportInitialize)(this.scoreGrid)).BeginInit();
            this.SuspendLayout();

            // 
            // scoreGrid
            // 
            this.scoreGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.scoreGrid.Columns.AddRange(new DataGridViewColumn[] {
                this.PlayerCol,
                this.ScoreCol,
                this.TimeCol
            });
            this.scoreGrid.Location = new Point(330, 50);
            this.scoreGrid.Name = "scoreGrid";
            this.scoreGrid.RowHeadersWidth = 51;
            this.scoreGrid.Size = new Size(375, 260);
            this.scoreGrid.TabIndex = 0;

            // Grid styling
            scoreGrid.BackgroundColor = Color.White;
            scoreGrid.BorderStyle = BorderStyle.FixedSingle;
            scoreGrid.RowHeadersVisible = false;
            scoreGrid.AllowUserToAddRows = false;

            scoreGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.LightGray;
            scoreGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            scoreGrid.ColumnHeadersDefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;

            scoreGrid.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleCenter;
            scoreGrid.DefaultCellStyle.Font = new Font("Segoe UI", 10F);

            scoreGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            scoreGrid.AutoSizeRowsMode = DataGridViewAutoSizeRowsMode.AllCells;

            scoreGrid.GridColor = Color.Silver;
            scoreGrid.AllowUserToResizeRows = false;
            scoreGrid.AllowUserToResizeColumns = false;

            scoreGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(240, 240, 240);

            // 
            // PlayerCol
            // 
            this.PlayerCol.HeaderText = "Player";
            this.PlayerCol.MinimumWidth = 6;
            this.PlayerCol.Name = "PlayerCol";
            this.PlayerCol.Width = 150;

            // 
            // ScoreCol
            // 
            this.ScoreCol.HeaderText = "Score";
            this.ScoreCol.MinimumWidth = 6;
            this.ScoreCol.Name = "ScoreCol";
            this.ScoreCol.Width = 90;

            // 
            // TimeCol
            // 
            this.TimeCol.HeaderText = "Time (sec)";
            this.TimeCol.MinimumWidth = 6;
            this.TimeCol.Name = "TimeCol";
            this.TimeCol.Width = 90;

            // 
            // resetButton
            // 
            this.resetButton.Location = new Point(80, 90);
            this.resetButton.Name = "resetButton";
            this.resetButton.Size = new Size(120, 32);
            this.resetButton.TabIndex = 1;
            this.resetButton.Text = "Reset Scores";
            this.resetButton.UseVisualStyleBackColor = true;
            this.resetButton.Click += new EventHandler(this.resetButton_Click);

            // 
            // closeButton
            // 
            this.closeButton.Location = new Point(80, 160);
            this.closeButton.Name = "closeButton";
            this.closeButton.Size = new Size(120, 32);
            this.closeButton.TabIndex = 2;
            this.closeButton.Text = "Close";
            this.closeButton.UseVisualStyleBackColor = true;
            this.closeButton.Click += new EventHandler(this.closeButton_Click);

            // 
            // HighScoreForm
            // 
            this.AutoScaleDimensions = new SizeF(8F, 20F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.ClientSize = new Size(800, 450);
            this.Controls.Add(this.closeButton);
            this.Controls.Add(this.resetButton);
            this.Controls.Add(this.scoreGrid);
            this.Name = "HighScoreForm";
            this.Text = "High Scores";
            this.Load += new EventHandler(this.HighScoreForm_Load);

            ((System.ComponentModel.ISupportInitialize)(this.scoreGrid)).EndInit();
            this.ResumeLayout(false);
        }

        #endregion

        private DataGridView scoreGrid;
        private DataGridViewTextBoxColumn PlayerCol;
        private DataGridViewTextBoxColumn ScoreCol;
        private DataGridViewTextBoxColumn TimeCol;
        private Button resetButton;
        private Button closeButton;
    }
}
